# Unsigned MCUboot images for simple in-house DFU.
CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# MCUboot is a single-threaded bootloader without BT, sensors, or analog IO.
CONFIG_ADC=n
CONFIG_ADC_NRFX_SAADC=n
CONFIG_I2C=n
CONFIG_I2C_NRFX=n
CONFIG_SPI=n
CONFIG_SPI_NRFX=n
CONFIG_SPI_NOR=n
